COPY (UAS)RTYACT.CTL,(SSBACKUP)SAME
COPY (UAS)RTYCTL.DAT,(SSBACKUP)SAME
COPY (SSINSTALL)RTYACT.CTL,(UAS)RTYACT.CTL
COPY (SSINSTALL)RTYCTL.DAT,(UAS)RTYCTL.DAT
COPY (SSINSTALL)RTYACT.CTL,(UAS)RTYACT.BAK
COPY (SSINSTALL)RTYCTL.DAT,(UAS)RTYCTL.BAK
R CKSUM
(UAS)RTYACT.CTL,(UAS)RTYACT.BAK,(UAS)RTYCTL.DAT,(UAS)RTYCTL.BAK

DEC ALL RD RD (UAS)RTYCTL.DAT,RTYACT.CTL
DIR/LIC (UAS)RTYCTL.DAT,RTYACT.CTL
SYSN
